default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  sslmode: <%= ENV['SSL_MODE'] %>

test:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  sslmode: <%= ENV['SSL_MODE'] %>

production:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  sslmode: <%= ENV['SSL_MODE'] %>
