default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mydatabase
  username: myuser
  password: mypassword
  host: localhost
  port: 5432

test:
  <<: *default
  database: test_mydatabase
  username: myuser
  password: mypassword
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
